// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace iBiblioteca.DATA.Models
{
    public class DbConfigurations
    {
        public string ConnectionString { get; internal set; }
    }
}