// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace iBiblioteca.DATA.Models;

public partial class DBIBIBLIOTECAContext : DbContext
{
    public DBIBIBLIOTECAContext()
    {
    }

    public DBIBIBLIOTECAContext(DbContextOptions<DBIBIBLIOTECAContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Tbautor> Tbautor { get; set; }

    public virtual DbSet<TbcapaLivro> TbcapaLivro { get; set; }

    public virtual DbSet<Tbcolecao> Tbcolecao { get; set; }

    public virtual DbSet<Tbeditora> Tbeditora { get; set; }

    public virtual DbSet<Tblivro> Tblivro { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=TARS;Initial Catalog=DBIBIBLIOTECA;Integrated Security=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Tbautor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TBAUTOR__3214EC2710FBECAC");
        });

        modelBuilder.Entity<TbcapaLivro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TBCAPA_L__3214EC2713C2175D");
        });

        modelBuilder.Entity<Tbcolecao>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TBCOLECA__3214EC273695FBD2");
        });

        modelBuilder.Entity<Tbeditora>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TBEDITOR__3214EC275E3D9B3F");
        });

        modelBuilder.Entity<Tblivro>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TBLIVRO__3214EC27E442566A");

            entity.HasOne(d => d.IdAutor1).WithMany(p => p.Tblivro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LIVRO_AUTOR");

            entity.HasOne(d => d.IdCapaNavigation).WithMany(p => p.Tblivro).HasConstraintName("FK_LIVRO_CAPA");

            entity.HasOne(d => d.IdColecaoNavigation).WithMany(p => p.Tblivro).HasConstraintName("FK_LIVRO_COLECAO");

            entity.HasOne(d => d.IdEditoraNavigation).WithMany(p => p.Tblivro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LIVRO_EDITORA");

            entity.HasMany(d => d.IdAutorNavigation).WithMany(p => p.IdLivro)
                .UsingEntity<Dictionary<string, object>>(
                    "TbLivroAutor",
                    r => r.HasOne<Tbautor>().WithMany()
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TB_LIVRO_AUTOR_AUTOR"),
                    l => l.HasOne<Tblivro>().WithMany()
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_TB_LIVRO_AUTOR_LIVRO"),
                    j =>
                    {
                        j.HasKey("IdLivro", "IdAutor").HasName("PK__TB_LIVRO__B74B39EA0971D3F2");
                        j.ToTable("TB_LIVRO_AUTOR");
                        j.IndexerProperty<int>("IdLivro").HasColumnName("ID_LIVRO");
                        j.IndexerProperty<int>("IdAutor").HasColumnName("ID_AUTOR");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}