// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using iBiblioteca.DATA.Services;

namespace iBiblioteca.DATA.Models;

[Table("TBCAPA_LIVRO")]
public partial class TbcapaLivro
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("NOME")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Nome")]
    public string Nome { get; set; }

    [Required]
    [Column("CAPA")]
    [Display(Name = "Imagem da Capa")]
    public byte[] Capa { get; set; }

    //#region ObterImagem

    //    public IActionResult GetImagem(int id)
    //    {
    //       var capalivro = oCapaLivroService
        
    //    var capaLivro = oVwLivroService.oRepositoryVwLivro.SelecionarPK(id);
           
    //        if (capaLivro != null && capaLivro.Capa != null)
    //        {
    //            return File(capaLivro.Capa, "image/jpg");
    //        }

    //        var placeholderImagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "placeholder.jpg");
    //        var placeholderBytes = System.IO.File.ReadAllBytes(placeholderImagePath);
    //        return File(placeholderBytes, "image/jpg");
    //    }
    //    #endregion

    [Column("CAMINHO")]
    [StringLength(255)]
    [Unicode(false)]
    [Display(Name = "Caminho da Imagem")]
    public string Caminho { get; set; }

    [InverseProperty("IdCapaNavigation")]
    public virtual ICollection<Tblivro> Tblivro { get; set; } = new List<Tblivro>();
}