// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iBiblioteca.DATA.Models;

[Table("TBLIVRO")]
[Index("IdAutor", Name = "IX_TBLIVRO_ID_AUTOR")]
[Index("Isbn", Name = "IX_TBLIVRO_ISBN")]
[Index("Titulo", Name = "IX_TBLIVRO_TITULO")]
public partial class Tblivro
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("TITULO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Column("ID_AUTOR")]
    public int IdAutor { get; set; }

    [Column("DATA_PUBLICACAO", TypeName = "date")]
    public DateTime DataPublicacao { get; set; }

    [Required]
    [Column("ISBN")]
    [StringLength(20)]
    [Unicode(false)]
    public string Isbn { get; set; }

    [Column("ID_EDITORA")]
    public int IdEditora { get; set; }

    [Column("PAGINAS")]
    public int Paginas { get; set; }

    [Column("PRECO", TypeName = "decimal(10, 2)")]
    public decimal Preco { get; set; }

    [Column("ID_CAPA")]
    public int? IdCapa { get; set; }

    [Column("ID_COLECAO")]
    public int? IdColecao { get; set; }

    [ForeignKey("IdAutor")]
    [InverseProperty("Tblivro")]
    public virtual Tbautor IdAutor1 { get; set; }

    [ForeignKey("IdCapa")]
    [InverseProperty("Tblivro")]
    public virtual TbcapaLivro IdCapaNavigation { get; set; }

    [ForeignKey("IdColecao")]
    [InverseProperty("Tblivro")]
    public virtual Tbcolecao IdColecaoNavigation { get; set; }

    [ForeignKey("IdEditora")]
    [InverseProperty("Tblivro")]
    public virtual Tbeditora IdEditoraNavigation { get; set; }

    [ForeignKey("IdLivro")]
    [InverseProperty("IdLivro")]
    public virtual ICollection<Tbautor> IdAutorNavigation { get; set; } = new List<Tbautor>();
}