// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace iBiblioteca.DATA.Models;
[Table("VW_LIVRO")]
[Index("IdAutor", Name = "IX_TBLIVRO_ID_AUTOR")]
[Index("Isbn", Name = "IX_TBLIVRO_ISBN")]
[Index("Titulo", Name = "IX_TBLIVRO_TITULO")]
public partial class Vwlivro
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("TITULO")]
    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Título")]
    public string Titulo { get; set; }

    [Column("ID_AUTOR")]
    public int IdAutor { get; set; }

    [Column("DATA_PUBLICACAO", TypeName = "date")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    [Display(Name = "Data da Publicação")]
    public DateTime DataPublicacao { get; set; }

    [Required]
    [Column("ISBN")]
    [StringLength(20)]
    [Unicode(false)]
    [Display(Name = "ISBN")]
    public string Isbn { get; set; }

    [Column("ID_EDITORA")]
    public int IdEditora { get; set; }

    [Column("PAGINAS")]
    [Display(Name = "Páginas")]
    public int Paginas { get; set; }

    [Column("PRECO", TypeName = "decimal(10, 2)")]
    [Display(Name = "Preço")]
    public decimal Preco { get; set; }

    [Column("ID_CAPA")]
    public int? IdCapa { get; set; }

    [Column("ID_COLECAO")]
    public int? IdColecao { get; set; }

    [Required]
    [Column("NOME_CONHECIDO")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Nome Conhecido")]
    public string NomeConhecido { get; set; }

    [Required]
    [Column("EDITORA")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Editora")]
    public string Editora { get; set; }

    [Required]
    [Column("COLECAO")]
    [StringLength(50)]
    [Unicode(false)]
    [Display(Name = "Coleção")]
    public string Colecao { get; set; }

    [Required]
    [Column("CAPA")]
    [Display(Name = "Capa")]
    public byte[] Capa { get; set; }

    // Propriedade de imagem para exibição
    [NotMapped] // Não será mapeada no banco de dados
    public System.Drawing.Image CapaImage
    {
        get
        {
            using (MemoryStream ms = new MemoryStream(Capa))
            {
                return System.Drawing.Image.FromStream(ms);
            }
        }
    }
    
}